// Code generated by ent, DO NOT EDIT.

package node

const (
	// Label holds the string label denoting the node type in the database.
	Label = "node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "node_name"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldPodInfo holds the string denoting the pod_info field in the database.
	FieldPodInfo = "pod_info"
	// Table holds the table name of the node in the database.
	Table = "node"
)

// Columns holds all SQL columns for node fields.
var Columns = []string{
	FieldID,
	FieldTimestamp,
	FieldPodInfo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
