// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NodeColumns holds the columns for the "node" table.
	NodeColumns = []*schema.Column{
		{Name: "node_name", Type: field.TypeString},
		{Name: "timestamp", Type: field.TypeString},
		{Name: "pod_info", Type: field.TypeString},
	}
	// NodeTable holds the schema information for the "node" table.
	NodeTable = &schema.Table{
		Name:       "node",
		Columns:    NodeColumns,
		PrimaryKey: []*schema.Column{NodeColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NodeTable,
	}
)

func init() {
	NodeTable.Annotation = &entsql.Annotation{
		Table: "node",
	}
}
